### ISSUE TITLE
Core Components links are broken

### ISSUE THREAD

**Issue by renato-bohler** [facebook/react-native-website#1780]
It seems that 3bb51b0d1f3ab224c638d19265b232437fc7068a added some links to "Core Components" that aren't valid (yet?).

These are the pages pointing to a broken link on the docs:
1. Learn The Basics > [What's going on here?](https://reactnative.dev/docs/tutorial#whats-going-on-here)
2. [Components and APIs](https://reactnative.dev/docs/components-and-apis)
3. [Handling Text Input](https://reactnative.dev/docs/handling-text-input)

They all point to https://reactnative.dev/docs/intro-react-native-components, which renders a 404 page.

On the `next` version of the docs, the link is valid though: https://reactnative.dev/docs/next/intro-react-native-components.

**Comment by Simek** [comment]
Thank you for the report. This issue should be fixed now thanks to version `0.62` cut. Can you confirm that?

**Comment by renato-bohler** [comment]
Hey there.

Hmm it seems that on the latest version this is indeed fixed... but if I go to the docs of version `0.61`, the problem still occurs. Examples:

1. https://reactnative.dev/docs/0.61/tutorial#whats-going-on-here
2. https://reactnative.dev/docs/0.61/components-and-apis
3. https://reactnative.dev/docs/0.61/handling-text-input

I'm not sure how far support goes for documentation of older versions, though.

**Comment by Simek** [comment]
Every example link you provided works for me (correct page loads, no 404). Can you clear your browser cache (in the most browsers `Ctrl/Cmd+Shift+R`). If this won't help can you describe what exactly is wrong with those links? 

BTW. Not all links from `0.62` or `next` should be valid in `0.61` docs.

**Comment by renato-bohler** [comment]
Oops, sorry about that. I didn't mean to say that these links are broken. I meant to say that these pages on the `0.61` version of the documentation still have broken links to the "Core Components" page.
